/**
 * This code was generated by Builder.io.
 */
import React from "react";

const GenAICard = ({ logo, company, title, type, image }) => {
  return (
    <article className="flex flex-col justify-center p-2 w-full max-w-[342px] min-h-[130px]">
      <div className="flex flex-col flex-1 justify-center p-2.5 w-full bg-white rounded-2xl border-2 border-violet-100 border-solid max-w-[326px]">
        <div className="flex gap-4 w-full min-h-[94px]">
          <div className="flex flex-col flex-1 shrink basis-0">
            <div className="flex gap-1 items-center w-full">
              <div className="flex items-start self-stretch my-auto w-[30px]">
                <div className="flex flex-col justify-center p-1 rounded border border-violet-100 border-solid min-h-[30px] w-[30px]">
                  <img
                    loading="lazy"
                    src={logo}
                    alt={`${company} logo`}
                    className="object-contain flex-1 w-full rounded-sm aspect-square"
                  />
                </div>
              </div>
              <span className="overflow-hidden self-stretch my-auto text-sm leading-none whitespace-nowrap text-slate-500">
                {company}
              </span>
            </div>
            <h3 className="mt-2 text-base font-semibold tracking-normal leading-none text-neutral-900">
              {title}
            </h3>
            <p className="mt-2 text-sm leading-none whitespace-nowrap text-slate-500">
              {type}
            </p>
          </div>
          <div className="flex overflow-hidden flex-col justify-center items-center w-16 h-16 bg-violet-100 rounded-lg">
            <img
              loading="lazy"
              src={image}
              alt={`${title} illustration`}
              className="object-contain w-16 aspect-square min-h-[64px] min-w-[64px]"
            />
          </div>
        </div>
      </div>
    </article>
  );
};

export default GenAICard;
