/**
 * This code was generated by Builder.io.
 */
import React from "react";

const GenAIFilter = ({ filters }) => {
  return (
    <div className="flex gap-1 items-start w-full text-sm font-semibold tracking-normal leading-none text-center whitespace-nowrap text-neutral-900">
      {filters.map((filter, index) => (
        <button
          key={index}
          className={`self-stretch px-3.5 py-1.5 border border-solid min-h-[32px] min-w-[44px] rounded-[32px] ${
            filter.active
              ? "text-white bg-slate-500 border-slate-400"
              : "bg-white border-slate-400"
          }`}
        >
          {filter.name}
        </button>
      ))}
    </div>
  );
};

export default GenAIFilter;
