/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AwardCard({ title, image, description, icon, backgroundImage, logo }) {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex grow max-md:mt-10">
        <div className="flex z-10 flex-col grow shrink-0 items-start my-auto mr-0 text-center basis-0 text-neutral-500 w-fit">
          {title && (
            <div className="self-end text-base font-medium tracking-wider leading-tight">
              {title}
            </div>
          )}
          <img
            loading="lazy"
            src={image}
            alt={title}
            className="object-contain mt-10 max-w-full aspect-[2.05] w-[129px] max-md:ml-2"
          />
          <div className="flex mt-5 text-lg leading-8">
            {icon && (
              <img
                loading="lazy"
                src={icon}
                alt=""
                className="object-contain shrink-0 self-start mt-7 w-6 bg-blend-normal aspect-square"
              />
            )}
            <div>{description}</div>
          </div>
        </div>
        {backgroundImage && (
          <div className="flex overflow-hidden relative flex-col items-end px-10 pt-96 aspect-[0.476] w-[198px] max-md:px-5 max-md:pt-24">
            <img
              loading="lazy"
              src={backgroundImage}
              alt=""
              className="object-cover absolute inset-0 size-full"
            />
            {logo && (
              <img
                loading="lazy"
                src={logo}
                alt=""
                className="object-contain w-14 aspect-[6.21]"
              />
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default AwardCard;
