// /**
//  * This code was generated by Builder.io.
//  */
// import React from "react";

// function CorporateSolutionCard({ icon, title, subtitle }) {
//   return (
//     <div className="flex items-start">
//       <img
//         loading="lazy"
//         src={icon}
//         alt=""
//         className="object-contain shrink-0 aspect-square w-[45px]"
//       />
//       <div className="flex flex-col mt-6">
//         <div className="pt-8 pr-0.5 pb-5 pl-8 max-w-full whitespace-nowrap border-t border-zinc-800 w-[104px] max-md:pl-5">
//           {title}
//         </div>
//         <div className="self-end">{subtitle}</div>
//       </div>
//     </div>
//   );
// }

// export default CorporateSolutionCard;
import React from "react";

function CorporateSolutionCard({ icon, title, subtitle }) {
  return (
    <div className="flex items-start">
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain shrink-0 aspect-square w-[45px]"
      />
      <div className="flex flex-col mt-6">
        <div className="pt-8 pr-0.5 pb-5 pl-8 max-w-full whitespace-nowrap border-t border-zinc-800 w-[104px] max-md:pl-5">
          {title}
        </div>
        <div className="self-end">{subtitle}</div>
      </div>
    </div>
  );
}

export default CorporateSolutionCard;
