// /**
//  * This code was generated by Builder.io.
//  */
// import React from "react";

// const companies = [
//   {
//     src: "https://cdn.builder.io/api/v1/image/assets/TEMP/890a7c3d4e1589fe53414e8e05635c91e26e5a4e6933dcbb5f8cce0e39451ed6?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
//     alt: "Company 1",
//     aspectRatio: "3.36",
//     width: "121px",
//   },
//   {
//     src: "https://cdn.builder.io/api/v1/image/assets/TEMP/e97bf8e533966d97669fdde895367946ef729fd790bbcb8b681df9bff266ea45?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
//     alt: "Company 2",
//     aspectRatio: "4.37",
//     width: "157px",
//   },
//   {
//     src: "https://cdn.builder.io/api/v1/image/assets/TEMP/6176ba45adad9443b8c13194a30d65a9d63082908a7bc07c85c91535c401b3f3?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
//     alt: "Company 3",
//     aspectRatio: "3.58",
//     width: "129px",
//   },
//   {
//     src: "https://cdn.builder.io/api/v1/image/assets/TEMP/71793fd226450f5f12cda753935a5794bcb4667b34ad6a4bec736a2df59abcb2?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
//     alt: "Company 4",
//     aspectRatio: "3.16",
//     width: "114px",
//   },
//   {
//     src: "https://cdn.builder.io/api/v1/image/assets/TEMP/300ee7977bfb48128e0077ab3e84bb7649c9c9ffaca1fbf5138b7c01bbba25fc?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
//     alt: "Company 5",
//     aspectRatio: "2.92",
//     width: "105px",
//   },
//   {
//     src: "https://cdn.builder.io/api/v1/image/assets/TEMP/ec1b5797012cb12ddd1e8bbcc61a456ff4544b4cd38c67885a506263b5451dae?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
//     alt: "Company 6",
//     aspectRatio: "3.69",
//     width: "133px",
//   },
//   {
//     src: "https://cdn.builder.io/api/v1/image/assets/TEMP/6bf37a9afe3b21693375649dd1f3ea40ba1ed30aac67174c97a3a9e557124b95?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
//     alt: "Company 7",
//     aspectRatio: "3.33",
//     width: "120px",
//   },
//   {
//     src: "https://cdn.builder.io/api/v1/image/assets/TEMP/c9d1ab6c1a5585ec154d05dba5353d752c7586780daafc8c0ff3b415c3983540?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
//     alt: "Company 8",
//     aspectRatio: "3.94",
//     width: "142px",
//   },
// ];

// function LearnersWorkSection() {
//   return (
//     <section className="flex flex-col justify-center items-center self-stretch px-20 py-20 mt-24 w-full bg-white max-md:px-5 max-md:mt-10 max-md:max-w-full">
//       <div className="flex flex-col max-w-full w-[1122px]">
//         <h2 className="self-center text-3xl font-bold leading-tight text-center text-neutral-800">
//           Our Learners Work at
//         </h2>
//         <div className="flex flex-wrap gap-3.5 mt-8 justify-center">
//           {companies.map((company, index) => (
//             <img
//               key={index}
//               loading="lazy"
//               src={company.src}
//               alt={company.alt}
//               className={`object-contain shrink-0 max-w-full aspect-[${company.aspectRatio}] w-[${company.width}]`}
//             />
//           ))}
//         </div>
//       </div>
//     </section>
//   );
// }

// export default LearnersWorkSection;
import React from "react";

const companies = [
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/890a7c3d4e1589fe53414e8e05635c91e26e5a4e6933dcbb5f8cce0e39451ed6?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
    alt: "Company 1",
    aspectRatio: "3.36",
    width: "121px",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/e97bf8e533966d97669fdde895367946ef729fd790bbcb8b681df9bff266ea45?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
    alt: "Company 2",
    aspectRatio: "4.37",
    width: "157px",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/6176ba45adad9443b8c13194a30d65a9d63082908a7bc07c85c91535c401b3f3?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
    alt: "Company 3",
    aspectRatio: "3.58",
    width: "129px",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/71793fd226450f5f12cda753935a5794bcb4667b34ad6a4bec736a2df59abcb2?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
    alt: "Company 4",
    aspectRatio: "3.16",
    width: "114px",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/300ee7977bfb48128e0077ab3e84bb7649c9c9ffaca1fbf5138b7c01bbba25fc?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
    alt: "Company 5",
    aspectRatio: "2.92",
    width: "105px",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/ec1b5797012cb12ddd1e8bbcc61a456ff4544b4cd38c67885a506263b5451dae?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
    alt: "Company 6",
    aspectRatio: "3.69",
    width: "133px",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/6bf37a9afe3b21693375649dd1f3ea40ba1ed30aac67174c97a3a9e557124b95?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
    alt: "Company 7",
    aspectRatio: "3.33",
    width: "120px",
  },
  {
    src: "https://cdn.builder.io/api/v1/image/assets/TEMP/c9d1ab6c1a5585ec154d05dba5353d752c7586780daafc8c0ff3b415c3983540?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13",
    alt: "Company 8",
    aspectRatio: "3.94",
    width: "142px",
  },
];

function LearnersWorkSection() {
  return (
    <section className="flex flex-col justify-center items-center self-stretch px-20 py-20 mt-24 w-full bg-white max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-col max-w-full w-[1122px]">
        <h2 className="self-center text-3xl font-bold leading-tight text-center text-neutral-800">
          Our Learners Work at
        </h2>
        <div className="flex flex-wrap gap-3.5 mt-8 justify-center">
          {companies.map((company, index) => (
            <img
              key={index}
              loading="lazy"
              src={company.src}
              alt={company.alt}
              className={`object-contain shrink-0 max-w-full aspect-[${company.aspectRatio}] w-[${company.width}]`}
            />
          ))}
        </div>
      </div>
    </section>
  );
}

export default LearnersWorkSection;
