/**
 * This code was generated by Builder.io.
 */
import React from "react";

function LearnPracticeEarnSection() {
  return (
    <section className="flex flex-col items-center self-stretch px-20 pt-20 pb-40 w-full bg-white max-md:px-5 max-md:pb-24 max-md:max-w-full">
      <div className="flex flex-col items-center mb-0 max-w-full w-[1133px] max-md:mb-2.5">
        <h2 className="text-3xl font-bold leading-tight text-center text-black max-md:max-w-full">
          Learn. Practice. Earn. Have Fun!
        </h2>
        <div className="flex gap-3.5 mt-8 max-w-full text-xs text-center whitespace-nowrap bg-neutral-100 text-neutral-500 w-[347px]">
          {/* Navigation tabs */}
        </div>
        <div className="self-stretch mt-14 max-md:mt-10 max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[42%] max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/d3b9d442a58c8825f86f83bafdd3911ad44ff343ca4d74f2cf109266365c85a2?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13"
                alt="Codekata illustration"
                className="object-contain grow w-full aspect-[1.72] max-md:mt-5 max-md:max-w-full"
              />
            </div>
            <div className="flex flex-col ml-5 w-[58%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col items-start text-base max-md:mt-4 max-md:max-w-full">
                <h3 className="text-3xl font-bold leading-tight text-black">
                  Codekata
                </h3>
                <p className="self-stretch mt-7 leading-7 text-neutral-500 max-md:max-w-full">
                  An interactive platform for programming practice with 1500+
                  coding problems curated by top programming veterans in the IT
                  industry. CodeKata tracks your performance and develops your
                  coding profile to showcase your skill set in the job
                  recruitment process. Boost your potential to crack coding
                  interviews by solving CodeKata problems.
                </p>
                <button className="px-4 py-3 mt-9 text-center text-white bg-indigo-600 rounded border border-indigo-600 border-solid">
                  Explore Codekata
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default LearnPracticeEarnSection;
