/**
 * This code was generated by Builder.io.
 */
import React from "react";

function OfferingCard({ icon, title, description, link }) {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col items-start p-6 mx-auto w-full text-base bg-white rounded-lg text-neutral-800 max-md:px-5 max-md:mt-4">
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="object-contain w-7 aspect-square"
        />
        <h3 className="mt-2 text-2xl font-bold leading-none">{title}</h3>
        <p className="self-stretch mt-4">{description}</p>
        <div className="flex gap-4 mt-14 font-medium text-green-600 max-md:mt-10">
          <a href="#" className="flex items-center">
            {link}
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/c112e1a4cf58af46b88143bc8284a39fdc6bd2b569c41cf74ee662e8d552b4c4?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13"
              alt=""
              className="object-contain shrink-0 ml-2 w-2.5 bg-blend-normal aspect-[0.63]"
            />
          </a>
        </div>
      </div>
    </div>
  );
}

export default OfferingCard;
