// /**
//  * This code was generated by Builder.io.
//  */
// import React from "react";

// function ZenClassCard({ icon, title, description }) {
//   return (
//     <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
//       <div className="flex flex-col items-start py-6 pr-20 pl-6 mx-auto w-full text-base bg-white rounded-lg text-neutral-800 max-md:px-5 max-md:mt-6">
//         <img
//           loading="lazy"
//           src={icon}
//           alt=""
//           className="object-contain w-7 aspect-square"
//         />
//         <h3 className="mt-2 text-2xl font-bold leading-none">{title}</h3>
//         <p className="mt-4">{description}</p>
//         <a href="#" className="flex gap-4 mt-8 font-medium text-green-600">
//           <span>Know More</span>
//           <img
//             loading="lazy"
//             src="https://cdn.builder.io/api/v1/image/assets/TEMP/cdabc98afaaa99fe4e116f99bdb44e5c358dcbfd39d3f96e8e2e792e6f0bd028?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13"
//             alt=""
//             className="object-contain shrink-0 my-auto w-2.5 bg-blend-normal aspect-[0.63]"
//           />
//         </a>
//       </div>
//     </div>
//   );
// }

// export default ZenClassCard;
import React from "react";

function ZenClassCard({ icon, title, description }) {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col items-start py-6 pr-20 pl-6 mx-auto w-full text-base bg-white rounded-lg text-neutral-800 max-md:px-5 max-md:mt-6">
        <img
          loading="lazy"
          src={icon}
          alt=""
          className="object-contain w-7 aspect-square"
        />
        <h3 className="mt-2 text-2xl font-bold leading-none">{title}</h3>
        <p className="mt-4">{description}</p>
        <a href="#" className="flex gap-4 mt-8 font-medium text-green-600">
          <span>Know More</span>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/cdabc98afaaa99fe4e116f99bdb44e5c358dcbfd39d3f96e8e2e792e6f0bd028?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13"
            alt=""
            className="object-contain shrink-0 my-auto w-2.5 bg-blend-normal aspect-[0.63]"
          />
        </a>
      </div>
    </div>
  );
}

export default ZenClassCard;
