/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Button({ children, primary, secondary }) {
  const baseClasses =
    "flex overflow-hidden justify-center items-center px-4 py-2 w-full text-center text-sm font-semibold tracking-normal leading-none rounded";
  const primaryClasses = "text-white bg-blue-700";
  const secondaryClasses = "text-blue-700 bg-white";

  return (
    <button
      className={`${baseClasses} ${primary ? primaryClasses : ""} ${
        secondary ? secondaryClasses : ""
      }`}
    >
      <span className="flex-1 shrink self-stretch px-32 my-auto w-full min-w-[240px]">
        {children}
      </span>
    </button>
  );
}

export default Button;
