/**
 * This code was generated by Builder.io.
 */
import React from "react";

function CertificateCard({ provider, title, type, imageUrl }) {
  return (
    <div className="flex flex-col justify-center p-2 w-full max-w-[374px] min-h-[154px]">
      <div className="flex flex-col flex-1 justify-center p-2.5 w-full bg-white rounded-2xl border-2 border-violet-100 border-solid max-w-[358px]">
        <div className="flex gap-4 w-full min-h-[118px]">
          <div className="flex flex-col flex-1 shrink basis-0 min-w-[240px]">
            <div className="flex w-full">
              <div className="flex flex-col w-[76px]">
                <div className="flex gap-1 items-center w-full">
                  <div className="flex items-start self-stretch my-auto w-[30px]">
                    <div className="flex flex-col justify-center p-1 rounded border border-violet-100 border-solid min-h-[30px] w-[30px]">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/0cc2127dde5ba90da65ee63e49f1a3f590f6b04e4d78291c0290c2c301842dec?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13"
                        alt=""
                        className="object-contain flex-1 w-full rounded-sm aspect-square"
                      />
                    </div>
                  </div>
                  <span className="overflow-hidden self-stretch my-auto text-sm leading-none whitespace-nowrap text-slate-500">
                    {provider}
                  </span>
                </div>
              </div>
            </div>
            <h3 className="mt-2 w-full text-base font-semibold tracking-normal leading-none text-neutral-900 overflow-hidden max-w-[258px]">
              {title}
            </h3>
            <div className="flex flex-col flex-1 mt-2 w-full text-sm leading-none">
              <div className="flex gap-2 w-full text-blue-700">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/d5f3d36ef9bb7b21c49e0ba0fc226ec2d912a1b319bf646dd10077e53312cc52?placeholderIfAbsent=true&apiKey=f22fb14ac5c9489cb8e97f6f25e87b13"
                  alt=""
                  className="object-contain shrink-0 self-start w-5 aspect-square"
                />
                <span>Make progress toward a degree</span>
              </div>
              <div className="flex overflow-hidden flex-col mt-2 w-full text-slate-500">
                <span className="w-full max-w-[258px]">{type}</span>
              </div>
            </div>
          </div>
          <div className="flex overflow-hidden flex-col justify-center items-center w-16 h-16 bg-violet-100 rounded-lg">
            <img
              loading="lazy"
              src={imageUrl}
              alt={`${title} icon`}
              className="object-contain w-16 aspect-square min-h-[64px] min-w-[64px]"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default CertificateCard;
